dist: trusty
language: python
jobs:
  include:
  - os: linux
    python: 3.8
    dist: xenial
    sudo: true
    env:
    - BUILD=PYPI
install:
- pip install -r requirements/dev.txt
- pip install flake8
script:
- flake8
deploy:
  skip_cleanup: true
  skip_existing: true
  provider: pypi
  user: apslite
  password:
    secure: Yy5Zt6fucTEeAumOgOzM1Zh5bX4EU1eGXCH+238IGnpnnlhVCO5XTor0pK0jKtvTIKzmvCeYzkGHmAr7F5DzKRXSTL4AjzIXPMdcdY3trKOUBJv1PHkBHXjXpEyxSW5PhvKAfn30S4TjnR3mCh774KZnKR/B1FAju5l6iRfklIwj6kirOaRl4s17TYGdutW31b/v019VuR6A6WI0+BFSE3sBkr0u9rVQHQU8HFjDNUfLFrtbjBWiyK3cwoGFMrPCkqXSeKN1aCoePotkS+2vZmhM1UgSFb5ATa6rIcNJeiWVHlDSyyG60KNq4OqJG+x3N8ZaFjIw2vIZ5FyRdSQLK3CW4eYZpsXLA8EtPcHCGe9P079wLzCej3kdMVNVzbRw/Wz/GUeZqEyfjEHYqebMb8JVclnP5kc8+ZIx434SexnH7dPpmPQnyjcJjuX/+Tf2MoMkE7WBIILr7dgak21kruW2NG+eeGz89YJgBXBySgSOD2gIgueIVVUAgduu/cKmayjV2XwFBKhzzvAMa2izBD6wTQT3Uq9BRkpWYSzvCVIEHGO4aFDQZ5Uh+CvcoBgIDwLwq/xotukFakTldI0ty+6o3c1oE3Lr6oQ4mQgAGpNw8ovUsEygwUJT2P4agrDpTmA/lPmFRDon6/XdcCJxqA7+nTT4VkUyso6mlSRA54Q=
  on:
    tags: true
    all_branches: true
    distributions: sdist
    condition: "$BUILD = PYPI"
    repo: cloudblue/product-sync
